# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-24 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_id', models.CharField(max_length=255)),
                ('resource_id', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('r_type', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('categories', models.ManyToManyField(to='edflex.Category')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together=set([('catalog_id', 'resource_id')]),
        ),
    ]
