# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-04-17 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edflex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='catalog_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='catalog_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.CharField(max_length=255),
        ),
    ]
